//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PhaseshiftInterfaces
{
    [Serializable]
    public class SystemStateMsg : Message
    {
        public const string k_RosMessageName = "phaseshift_interfaces/SystemState";
        public override string RosMessageName => k_RosMessageName;

        //  ==============================
        //  PhaseShift Digital Twin
        //  Authoritative System Contract
        //  ==============================
        public BuiltinInterfaces.TimeMsg stamp;
        //  -------- High-Level System Phase --------
        public byte phase;
        public const byte PHASE_BOOT = 0;
        public const byte PHASE_CONNECTING = 1;
        public const byte PHASE_SLAM_ACTIVE = 2;
        public const byte PHASE_MAP_SAVED = 3;
        public const byte PHASE_NAV_READY = 4;
        public const byte PHASE_NAVIGATING = 5;
        public const byte PHASE_ERROR = 6;
        //  -------- Error Handling --------
        public bool has_error;
        public string error_message;

        public SystemStateMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.phase = 0;
            this.has_error = false;
            this.error_message = "";
        }

        public SystemStateMsg(BuiltinInterfaces.TimeMsg stamp, byte phase, bool has_error, string error_message)
        {
            this.stamp = stamp;
            this.phase = phase;
            this.has_error = has_error;
            this.error_message = error_message;
        }

        public static SystemStateMsg Deserialize(MessageDeserializer deserializer) => new SystemStateMsg(deserializer);

        private SystemStateMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.phase);
            deserializer.Read(out this.has_error);
            deserializer.Read(out this.error_message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.phase);
            serializer.Write(this.has_error);
            serializer.Write(this.error_message);
        }

        public override string ToString()
        {
            return "SystemStateMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nphase: " + phase.ToString() +
            "\nhas_error: " + has_error.ToString() +
            "\nerror_message: " + error_message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
